version: '3.8'
services:
  app:
    image: app-image
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      SPRING_DATASOURCE_USERNAME: rm98057
      SPRING_DATASOURCE_PASSWORD: 250899
    depends_on:
      - oracle-db
    stdin_open: true
    tty: true

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 250899
      ORACLE_ALLOW_REMOTE: 'true'
    volumes:
      - oracle-data:/u01/app/oracle

volumes:
  oracle-data:
    driver: local